### PR TITLE
Add AppData file.

### PR DESCRIPTION
**Pull request by dchristidis**
I copied the content from the [GNOME Wiki](https://wiki.gnome.org/Apps/GnomeTwitch). I think that the Wiki page, the AppData file and README.md should be kept in sync.

This is a first step, but there are some issues:
- According to [the specification](https://people.freedesktop.org/~hughsient/appdata/), the screenshots should (1) have an aspect ratio of 16:9 and (2) should use the vanilla GNOME look-and-feel.
- The metadata should be translatable, but I'm not unsure on how to do this with meson.
- The files used to generate packages should be updated accordingly.

Out of curiosity, why is it named `com.gnome-twitch.app.desktop` instead of `com.gnome-twitch.desktop`?

### CODE REVIEW

**Comment by Ippytraxx** [comment]
Interesting, never looked into the appdata stuff but as you pointed out it has some good general guidelines. I'd like to keep this PR open as a reminder to fix the points listed if that's okay with you.

Also the desktop file has to be named so because the desktop filename has to be identical to the app id which is `com.gnome-twitch.app` for notifications to work.

**Comment by dchristidis** [comment]
Sure, there's no real benefit of accepting it at this time. It will only become useful when distributions provide their own packages.

**Comment by dengelt** [comment]
Some questions/comments on the mentioned points that "block" this PR:

1. I looked at the specification, and the relevant part regarding screenshots seems to be this: 

  > Use the default visual and theme settings, including the default font, icons, and window controls. Avoid including your own tweaks to the standard distribution offering. 

  So the question is how "default" and "standard distribution offering" is to be understood. From my point of view, these terms refer to the default that the upstream author sets for the application, i.e. how it looks right after installing, without the user having to adjust any settings. So I think the usage of the dark theme for the screenshots is not a problem, since it is an application default. Also it would be confusing to the user if the screenshot had a light theme and the actual app then used a dark theme.

  Also, the aspect ratio seems to be 16:9 now, so that's fine.

2. I think I know how to make it translatable, I'll try it either today, tomorrow or on Friday. If it works like I think it should, I can either make a pull request on your pull request branch if that's possible or make a pull request once this one is merged, whatever is more desired.

3. I don't know what you mean by that. The appdata file is simply installed to `/usr/share/appdata`, and that should be enough. The distributions will then parse those files to include them in their databases.

**Comment by dchristidis** [comment]
Thanks for your feedback. Replying to your points:

1. I think that the minimize and maximize buttons on the header bar are part of the "window controls" that cannot be considered standard.

2. That would be fantastic. If you could submit a pull request against my `appdata` branch, I would merge it right away.

3. I know that, at least for the RPM package, a new entry has to be added to the spec file. I'm not familiar with other package formats.

**Comment by dengelt** [comment]
Update on old points and some new points:

1. You are right, I didn't even notice those. I always had those enabled, so I forgot they weren't there by default.

2. Could you update your branch to the current master? I plan to also add the German translation strings for the appdata file right away to test if everything works, and doing that on an old translation would be counter-productive since it would introduce conflicts that would have to be resolved when the branch is merged. Also I'll need to add a LINGUAS file listing all translated language codes, and it would be nice if the "new" translation's language codes (pt and hu) would be there from the start, else they'd have to be added after the merge into master.

3. Ok I didn't know that. In Debian nothing else is needed, so I don't know what needs to be done for the RPM (and possibly Arch?) packages.

4. I used `appstream-util validate` to check the desktop file and got 3 errors, which will be outlined in this and the following two points:
  > • tag-missing           : \<translation\> not specified

  According to the [specification](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#spec-component-filespec) `<translation>` is an optional tag, but it might still be good to provide it, although I didn't exactly get what the "translation domain" should be. But it's late now so I'll read it again tomorrow. The specification also lists some other tags that might be good to include.

5. 
  > • url-not-found         : \<screenshot\> url not found [https://github.com/Ippytraxx/gnome-twitch/blob/master/data/screenshots/scrot_games.png?raw=true]

  The screenshot URL seems to have changed, and I think keeping it a link to the master branch is not the right way to do it because of this very problem. The appstream file will probably need to be valid for a long time, e.g. for the version that enters Debian stable at least 2+2 years (for the stable and oldstable cycle), and that can not be guaranteed with a link to a file in the master branch. The problem now is that if we use a versioned link (i.e. one to a tag like v0.3.0 for the next release), we'd have to set the URL before it exists, because if we tag a release and **then** update the URL in the appdata file, that modification will not be part of the release. Maybe someone can come up with a different way than the first one (i.e. set the versioned link before it exists) that doesn't involve hosting the screenshots outside of GitHub, but I can't think of anything right now.

6. 
  > • style-invalid         : Content before \<ul\> is too short [149], at least 300 characters required
  
  Maybe someone could come up with a longer description.

**Comment by dchristidis** [comment]
Good call on **2**. The branch is now up-to-date.

Regarding **5**, pointing to the master branch might not be an issue. Most GNOME applications seem to do the same thing. You are absolutely right though that screenshots must not be deleted.

**Comment by dchristidis** [comment]
I am retiring this pull request as @TingPing's work in #215 is clearly the way to go.

**Pull request closed without merging**
