### PR TITLE
build: Various cleanups

### PR DESCRIPTION
**Pull request by TingPing**
One thing I did want to ask about is the fact you don't install appdata/desktop files on Windows. This is a weird artificial limitation considering msys/mingw/cygwin can use them.

### CODE REVIEW

**Comment by vinszent** [comment]
I can't remember the exact reason but I think it was something to do with msgfmt on Cygwin not working. I'll have to recheck it, now that you've changed the build file. But thanks for cleaning up the build files!

**Comment by TingPing** [comment]
Also some more comments, now that the backends are not subprojects they should probably be moved for clarity, the new option names are far too long for a human, and the library split is a bit odd (who will actually use that?)

**Comment by vinszent** [comment]
Yes I'll see if I can do some renaming but I still want to keep things cohesive.

The library split is to allow building plugins on Windows which doesn't allow undefined references when linking like Linux does. I took this approach from [Gedit](https://git.gnome.org/browse/gedit/tree/gedit/Makefile.am) which has the majority of its functionality in a shared lib (libgedit).

**Comment by TingPing** [comment]
> The library split is to allow building plugins on Windows which doesn't allow undefined references when linking like Linux does. I took this approach from Gedit which has the majority of its functionality in a shared lib (libgedit).

I'm pretty sure that isn't accurate, If what you merged here still builds for you then it is relying upon undefined references. If that is working I can further clean it up.

**Comment by vinszent** [comment]
In the current revision when building the plugins, they will be linked against the shared lib i.e. no undefined references. Before on Linux before I could just not pass `-Wl,--no-undefined` by setting `b_lundef` to false with Meson and allow undefined references (which later are defined at runtime).

The problem is well described on [this page](http://edll.sourceforge.net/). I've basically opted for option 2 from that page and I am building a sub-library that contains all shared functionality.

I don't like option 1 because I'll have to have a whole bunch of #ifdefs littered throughout my code. I couldn't get option 3 to work for the life of me and option 4 just adds another library that I don't want to use.

**Comment by TingPing** [comment]
> In the current revision when building the plugins, they will be linked against the shared lib

Not in what I wrote they won't. So it must be failing in Windows?

**Comment by vinszent** [comment]
I'll have to test it, but from what I can see it should you haven't changed anything in that regard. They are still being linked against `gt_module_dep` which is `gt_library_dep` for example [here](https://github.com/vinszent/gnome-twitch/blob/master/subprojects/player-backend-gstreamer-cairo/meson.build#L23)

**Comment by TingPing** [comment]
`gt_module_dep` only points to `gt_library_dep` if linking against an installed library which [isn't the case on Windows](https://github.com/vinszent/gnome-twitch/blob/master/data/packages/windows/PKGBUILD#L66-L68).

**Comment by vinszent** [comment]
Oh right yes you are correct!

**Comment by TingPing** [comment]
It avoids linking unnecessarily on Linux, if that can't work on Windows just replace `gt_module_dep` with `gt_library_dep` again. Sorry I didn't test that.

**Comment by vinszent** [comment]
I guess it's possible to put:
```meson
if build_machine.system() == 'windows'
  deps += gt_module_dep
endif
```
in each plugin build file.

**Comment by TingPing** [comment]
Honestly its minor enough that we don't really need to workaround it per platform. Oh no Linux builds in .14 seconds instead of .1.

**Comment by vinszent** [comment]
So anyways I rewrote it 😛 , you can have a look [here](https://github.com/vinszent/gnome-twitch/commit/3fbd35c715b095513142904aa4d375745e3174f8). I've tested it, and it builds on Windows.

Now we only build the sub-library on Windows and make all plugins link to it. Otherwise we just compile any shared functionality into the main executable and skip any sub-library business. It's cleaner this anyways imo.

Also I've merged all the build-player-backend-... flags into a single flag. So now you can simply specify
`-Dbuild-player-backends=gstreamer-cairo,gstreamer-opengl`.

**Pull request merged**
