### PR TITLE
Added spanish translation

### PR DESCRIPTION
**Pull request by ElJava**

### CODE REVIEW

**Comment by dengelt** [comment]
A few things I noticed:

1. Please fill out the template comment at the top. You can look at the other translations and just replace the name, copyright years, and language name. If you don't want to put in your real name, you can use a pseudonym like your github account name.

2. The language code in the file should be `es`, not `es_ES`, like the file name.

3. The version is missing in the `Project-Id-Version` field. It should be `gnome-twitch 0.2.0` instead of `gnome-twitch`.

4. The field  `Report-Msgid-Bugs-To` should contain the bugtracker URL: `https://github.com/Ippytraxx/gnome-twitch/issues/new\n`.

5. Please add yourself into the `Last-Translator` field. If you used a pseudonym in the copyright notice, you can use it here too.

6. Also please add yourself into the `translator-credits` field, like above.

7. The translation for "About" has a whitespace at the end that is not in the original string and thus should be removed.

If you don't know how exactly some entry should look like, you can look the the other translations or ask here.

**Comment by ElJava** [comment]
Hi!
Firstly thanks for your reply.
It's the first time I translate anything and I am still unfamiliar with the environment. I did a straight translation with Poedit and I did not notice the metadata in the po file.
I've just pushed a new version with those problems fixed, if there is still something wrong just let me know it.

**Comment by dengelt** [comment]
Hi,
just two more minor things:

1. The year in the copyright statement should probably just be `2016` instead of `2015-2016`, except if you have been working on that translation since 2015 ;)

2. The email address that appears in the copyright statement should also appear in the `Last-Translator` field and the `translator-credits` field in the same way as it is in the copyright statement.

I haven't used Poedit much, but I remember it doing some weird stuff sometimes that I had to correct manually. I don't know which distro you are using, but in Debian (which I am using) the packages `i18nspector` and `gettext-lint` contain some helpful tools (mainly `i18nspector` and `POFileChecker`) for finding these kinds of small things that we humans easily overlook.

**Comment by AlejandroC90** [comment]
I use Gnome Twitch almost daily so I wanted to help to the Spanish Translation until I saw this, He didn't fix the commit and it's been almost 3 months and I pretty sure some new Strings were added, what should I do?, send a new pull request?.

**Comment by vinszent** [comment]
Yeah sure, you can just merge the new pot file into his one if you want, or translate from scratch. You can send a new PR after that, I'll close this one when you do. Thanks in advance ;)

**Comment by vinszent** [comment]
Spanish translation has been merged in from Zanata.

**Pull request closed without merging**
