### PR TITLE
Update Polish translation 170405

### PR DESCRIPTION
**Pull request by piotrdrag**
Plus a few i18n fixes.

### CODE REVIEW

**Comment by vinszent** [comment]
@piotrdrag What's the general consensus on translating error messages? Messages like [this](https://github.com/vinszent/gnome-twitch/blob/master/src/gt-twitch.c#L341) that are really just meant for developers or power users. If I mark those for translating there will be a whole lot more to translate that isn't really super relevant for the end user.

**Comment by piotrdrag** [comment]
The rule of thumb is: if a user can see it in the UI (as opposed to e.g. logs), then it should be marked for translation. Are those visible, and if so, how? If they’re hidden under “Details” or some such, then they could be left in English.

**Comment by vinszent** [comment]
Ok, generally the errors are under "Details" like you said although I might have to mark a few more strings for the error messages that show up in the notification bar.

**Comment by piotrdrag** [comment]
Anything I can do to get this merged?

**Comment by vinszent** [comment]
Sorry for the delay. I might need to mark a few more strings for translation as I wrote above, but I'll let you know.

**Comment by piotrdrag** [comment]
Thank you!

**Pull request merged**
