### PR TITLE
Flatpak take 2

### PR DESCRIPTION
**Pull request by mattiasb**
Another solution for #157 which I think makes a little more sense. 

For testing, remove the top commit before running flatpak-builder.

### CODE REVIEW

**Comment by vinszent** [comment]
Why are you building all player backends? Only the GStreamer-Cairo backend will work properly due to not using OpenGL.

**Comment by mattiasb** [comment]
All three are working fine on my Intel system. The problem was with NVidias blob right? It's easy to turn off the clutter- and OpenGL backends ofcourse.

**Comment by mattiasb** [comment]
Turn off building I mean

**Comment by vinszent** [comment]
Hmm yeah I guess so.  I'd probably remove the Clutter backend as it just pulls in unecessary dependencies, the GStreamer-OpenGL backend does virtually the same thing as the Clutter one anyways.

I'll merge this next weekend after exams.

**Comment by mattiasb** [comment]
Sure! Either way works for me. :)

**Comment by vinszent** [comment]
Sorry for the long wait, but thanks for your work nonetheless! I currently have a VPS to host the OSTree, just haven't had enough time to set it up, will try to do it in the coming weeks.

**Comment by mattiasb** [comment]
Thanks a lot for merging and LOTS of thanks for gnome-twitch. :)

**Comment by TingPing** [comment]
For anybody interested I have made a working flatpak file and host it on my server: https://github.com/TingPing/flatpak-packages

**Comment by vinszent** [comment]
@TingPing Thanks a lot for this. I was planning on doing this myself, but tbh I never got around to it. I'll set up the FlatPak and wiki article to install from your server if that's fine with you.

**Comment by TingPing** [comment]
@vinszent No problem.

**Pull request merged**
