### PR TITLE
Update Fedora package

### PR DESCRIPTION
**Pull request by TingPing**

### CODE REVIEW

**Comment by vinszent** [comment]
Thanks for cleaning this up! I've been meaning to get to it, just haven't had the time.

**Comment by TingPing** [comment]
By the way, I tried to package this in Copr but for what ever reason their build system uses ascii encoding so Meson fails. I am not sure the work around for this atm, maybe I need to find somebody in Fedora to change that stupidity to UTF8...

**Comment by vinszent** [comment]
Ok sure, no problem.

**Comment by julianrichen** [comment]
Hello, looking at the changes:

https://github.com/vinszent/gnome-twitch/pull/233/files#diff-4b9d7c6e00a38d2e2a168f028be6f7caR15

Isn't the requirement GTK 3.20.0 not 3.2.0?

**Comment by TingPing** [comment]
> Isn't the requirement GTK 3.20.0 not 3.2.0?

Yup, typo.

**Pull request merged**
